title: Sravya Arutla
# logo: /assests/img/sravya_headshot.png
logo: /assets/img/Sravya_A.jpg
description: Data Engineer
# show_downloads: False


remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins
